#!/usr/bin/env php

<?php

require __DIR__ . '/test-init';

use BapCat\Values\Email;

use BapCat\CoolThing\User;
use BapCat\CoolThing\UserId;
use BapCat\CoolThing\UserGateway;
use BapCat\CoolThing\UserRepository;
use BapCat\CoolThing\UserNotFoundException;

$user = User::create(new Email('corey@narwhunderful.com'));
echo $user;
echo "\n\n";
echo json_encode($user);
echo "\n\n";

echo json_encode($gate->query()
  ->select('id', 'email', 'full_email', 'first_name', 'last_name', 'full_name')
  ->get()
);

echo "\n\n";

echo json_encode($repo->orderByEmail()->get());

echo "\n\n";

try {
  $repo->withEmail(new Email('i@dont.exist'))->first();
} catch(UserNotFoundException $ex) {
  echo 'User not found (this is supposed to happen)';
}
