#!/usr/bin/env php

<?php

require __DIR__ . '/test-init';

use BapCat\Values\Text;

use BapCat\CoolThing\User;
use BapCat\CoolThing\UserGateway;
use BapCat\CoolThing\UserRepository;

$user = $repo->first();
$user->first_name = new Text('Not Corey');
$repo->save($user);
var_dump($user);
