#!/usr/bin/env php

<?php

require __DIR__ . '/test-init';

use BapCat\Values\Email;

use BapCat\CoolThing\User;
use BapCat\CoolThing\UserGateway;
use BapCat\CoolThing\UserRepository;

$user = User::create(new Email('corey+inserttest@narwhunderful.com'));
$repo->save($user);
var_dump($user);
