#!/usr/bin/env php

<?php

require __DIR__ . '/test-init';

use BapCat\Phi\Phi;
use BapCat\Values\Email;
use BapCat\Values\Text;

use BapCat\Remodel\Registry;
use BapCat\Remodel\EntityDefinition;
use BapCat\CoolThing\User;
use BapCat\CoolThing\UserId;
use BapCat\CoolThing\UserGateway;
use BapCat\CoolThing\UserRepository;
use BapCat\CoolThing\UserNotFoundException;

$registry = $ioc->make(Registry::class, [$ioc]);

$def = new EntityDefinition(User::class);
$def->required('email', Email::class);
$def->optional('first_name', Text::class);
$def->optional('last_name', Text::class);
$def->virtual('full_email', Text::class, ['first_name', "' '", 'last_name', "' <'", 'email', "'>'"]);
$def->virtual('full_name', Text::class, ['first_name', "' '", 'last_name']);

$registry->register($def);

$user = User::create(new Email('corey@narwhunderful.com'));
echo $user;
echo "\n\n";
echo json_encode($user);
echo "\n\n";

$gate = new UserGateway($connection);
echo json_encode($gate->query()
  ->select('id', 'email', 'full_email', 'first_name', 'last_name', 'full_name')
  ->get()
);

echo "\n\n";

$repo = new UserRepository(Phi::instance(), $gate);
echo json_encode($repo->orderByEmail()->get());

echo "\n\n";

try {
  $repo->withEmail(new Email('i@dont.exist'))->first();
} catch(UserNotFoundException $ex) {
  echo 'User not found (this is supposed to happen)';
}
