#!/usr/bin/env php

<?php

require __DIR__ . '/test-init';

$user = $repo->withRelations()->first();

echo json_encode($user);
echo "\n";
echo json_encode($user->posts);
echo "\n";
echo json_encode($user->posts[0]->creator);
