#!/usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

use BapCat\Interfaces\Values\Value;
use BapCat\Phi\Phi;
use BapCat\Persist\Drivers\Filesystem\FilesystemDriver;
use BapCat\Tailor\Tailor;
use BapCat\Tailor\PersistTemplateFinder;
use BapCat\Tailor\Compilers\PhpCompiler;
use Illuminate\Database\MySqlConnection;

// Grab filesystem directories
$persist = new FilesystemDriver(__DIR__ . '/templates');
$templates = $persist->get('/');
$compiled  = $persist->get('/');

// TemplateFinders are able to find and use raw/compiled templates
$finder = new PersistTemplateFinder($templates, $compiled);

// Compilers translate raw templates into compiled ones
$compiler = new PhpCompiler();

// Create an instance of Tailor to actually do the autoloading
$tailor = new Tailor($finder, $compiler);

$connection = new MySqlConnection(new PDO('mysql:host=localhost;dbname=test', 'root', ''), 'test');

//-----------------------------------------------------------

use BapCat\Values\Email;
use BapCat\Values\Text;

class CoolIdentifier extends Value {
  private $id;
  
  public function __construct($id) {
    $this->validate($id);
    $this->id = (integer)$id;
  }
  
  private function validate($id) {
    if(filter_var($id, FILTER_VALIDATE_INT, ['options' => ['min_range' => 0]]) === false) {
      throw new InvalidArgumentException("Expected a valid ID, but got [$id] instead");
    }
  }
  
  protected function getRaw() {
    return $this->id;
  }
}

use BapCat\Remodel\Registry;
use BapCat\Remodel\EntityDefinition;
use BapCat\CoolThing\User;
use BapCat\CoolThing\UserGateway;
use BapCat\CoolThing\UserRepository;

$registry = new Registry($tailor);

$def = new EntityDefinition(User::class);
$def->id(CoolIdentifier::class);
$def->required('email', Email::class);
$def->optional('first_name', Text::class);
$def->optional('last_name', Text::class);
$def->virtual('full_email', Text::class, ['First_Name', "' '", 'Last_Name', "' <'", 'Email', "'>'"]);
$def->virtual('full_name', Text::class, ['First_Name', "' '", 'Last_Name']);

$registry->register($def);

$user = User::create(new Email('corey@narwhunderful.com'));
var_dump($user);

$gate = new UserGateway($connection);
var_dump($gate->query()
  ->select('id', 'email', 'full_email', 'first_name', 'last_name', 'full_name')
  ->get()
);

$repo = new UserRepository(Phi::instance(), $gate);
var_dump($repo->get());
