#!/usr/bin/env php

<?php

require __DIR__ . '/test-init';

use BapCat\CoolThing\User;

$user = $repo->first();

echo json_encode($user->posts);
echo "\n";
echo json_encode($user->posts[0]->creator);
